### PR TITLE
Add Memory mapped reset and direct vector read to NEKO from MicroBlaze

### PR DESCRIPTION
**Pull request by d1duarte**
```
Add Memory mapped reset and direct vector read to NEKO from MicroBlaze
```

### CODE REVIEW

**Comment by zwabbit** [comment]
I'm prepared to merge this, but I have one question and two notes that I want you to be aware of.

1) Does Vivado implement this without timing errors? A 2K wide bus is pretty wide and a too wide memory bus was one of the problems we had in previous iterations of MIAOW.

2) I'm going to be moving all of the VGPR read addresses way down into the address space. If I need to change addresses for the configuration and other control registers below the VGPR, I want to have the address space available for flexibility.

3) The register interfaces exist in this iteration of Neko, and likely always will, but a future iteration that drops the FPGA specific compute unit top level will likely not have a register interface and will require the usage of memory instructions to shuffle data between the register files and memory and a user will need to read the resulting values from memory instead of directly from the register file.

**Comment by d1duarte** [comment]
Hi,

1) I'm using an ADM-PCIE-7V3 board which contains a Xilinx® Virtex® 7 :
XC7VX690T-2 - FFG1157C which is a bit larger than the VC707 you are using.
In my implementation I have no timing issues (see attachment), my worst
negative slack in setup is 0.912ns and in hold it is 0.035ns. I'm not sure
if this holds true for your board, do you want me to try and implement this
for your board?

2) The addresssing is not an issue, go ahead and place it where it best
suits the application.

3) This is useful as a debug tool, once the memory instructions are ready
we can use them instead of this hack! Also I was thinking in adding a
similar interface to write the vector registers for debug purposes are you
interested in that at this moment?

Best,

Pedro Duarte

2016-03-05 18:46 GMT+00:00 zwabbit notifications@github.com:

**Comment by zwabbit** [comment]
In that case it might be better to have you do the write interface as well and have them both use the same address range for input, as right now there's not a way to load values into the vgpr with the memory instructions broken. Then once that's done, you can submit a combined pull request and I can merge that in.

**Comment by d1duarte** [comment]
Just finished correcting and verifying the functionality of the vector register read and writes. Also the worst negative slack remains positive at 0.242ns for setup and 0.020ns for hold time in my board's implementation.

PS: I've also added a simple tcl script which automatically creates/connects the interconnect's interface ports.

**Comment by zwabbit** [comment]
One recommendation for the way you're doing the write masks, I would suggest ORing them whenever one of the VGPR write registers get written to, and also have an option to clear the entire register when the need arises. Otherwise allowing only one bank of the VGPR to be written at a time seems potentially cumbersome.

**Comment by d1duarte** [comment]
The 'or' is occurring between the current mask, which is in "singleVectorWrDataMask", and the mask of the value which is written to (value attribution to "singleVectorWrDataMask_next"). 
The clear register is a good idea and I'll also add a pair of registers to do a manual mask set.

**Comment by d1duarte** [comment]
I've implemented the suggested changes and also allowed for the mask to be directly written to.

**Pull request merged**
